# Generated by Django 2.1.2 on 2018-11-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplines', '0003_auto_20180906_1714'),
        ('rooms', '0002_auto_20181109_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('THR', 'Banca Teórica'), ('PRT', 'Banca Prática')], default='THR', max_length=3)),
                ('selected_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('weight', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disciplines', models.ManyToManyField(to='disciplines.Discipline')),
                ('free_rooms', models.ManyToManyField(to='rooms.Room')),
            ],
        ),
    ]
