# Generated by Django 2.1.2 on 2018-11-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(choices=[('A', 'Bloco A'), ('B', 'Bloco B'), ('C', 'Bloco C'), ('D', 'Bloco D')], default='A', max_length=1)),
                ('floor', models.IntegerField()),
                ('identifier', models.CharField(max_length=2)),
            ],
        ),
    ]
