# Generated by Django 2.1.2 on 2018-11-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.CharField(choices=[('T', 'Térreo'), ('1', 'Primeiro'), ('2', 'Segundo')], default='T', max_length=1),
        ),
    ]
