language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python manage.py test
secure: lySjRTC+PMP209C2zrxVy8YYoHCiBredB1HXwahzHzd8X0cy6aAF22IWsS2hwx0pphQKyjrfh4ykxxLW8r4PoabjAGYAdlYN64DeKxRET5bwvGGPsHNjCR3MFoBUhGXkQaLQ72O2v6ttcTOumutZbUEdHSuKFFCmobCO2DXuduPcn2X6BGVWM4OGsUyB9pVm995/6/5z8FDDBIhf9Ztx0VOl7FCvW80Xsxe6jzQEa67bS2oo/JbfjoYMZYI4RJdjpPzGoMLPPwULTPRYUD52u6WZneAlLANMp7EGLJI+RDewx/chyPyPSKjQoXp778mWoyesofZcSOSyX5Vgt326KhURr2EsAY4tfaGj9TFhnrF+G81o7CO2+zfY4DxUNkKQ4iVmawXYgU41jtWcYNisnCRhOSzvl+HgB87ZY8zARj2sSAVz/9wK4pe7tHniwUf/iZNUCggRlvzZArlToTNNjFQ0zOLCy2d7Y0AyhMNnFgX5RpuDRO4I5aunua7EdkcxLN8coPnLeRAVlM8F1WFI+d+cNSyOaP5vY2q0nNdSoGopAB13lQ5ZD1h0PgkvpY/HzhuXQ46WroNRniFUw4VxZP0Q4+ksGewnOp1KSrqrtQR1xfeqQowK0JXNYq8WB834z5iSlYo5UUuEehvbqjjE3TkHc6vBo0r/IKvrN3s92zo=
deploy:
  provider: heroku
  api_key:
    secure: EKiXrMz9agRFXmPscQfJqrp4caSTBBt052GOCNmiHdt37WmPjP5u7uJTEj+PErOVfx/Z53+L0J+e+stQYiBQgfYqTRntObPD2dZ9wc4b1kaExFrnrHdth8jQiHtpbRgJKVxJqAkf3Lu2XEx56hiA7XTCiFnFp70BAzVXcnv1cwuycLb73hTR+ikTTw8QF58YzPfM0uqCrZWtQS3JSwAQoGZDlvFc5tpvpW+OBIfDhd30im2pD696PuNcbOtJyH/iRm7+zH1n4FN4yfx128eHQN14lat1dhMIaw9DhthRcTxzsVhysLg5swoS/IN8MGfi3dLWi44gp9V3p98f/o59fLE8aCBrx0u8THGD4amva18Dwsc8PYTtQNleRBFiuKatEIDTlcHqdOZoYeVc78rDpd1AJrGnoDVFeWZuqoI+s1KzKiEnveOQmG6RkKkfTIihjd8FnCKNmQOlCtPgxp9XoXtaeyEdi7jQXckJ3B/Y7JxaacIkgvRrKrpk+y1QEc2dcmtaPY1XPc3v0cDNs7OcQ1gvf+5wW4Vv1M76O5wHslwvJEFF7+ElchvHvdCv94r5QN+lE/AEZa8z8WOuC6LD3ra5jrUKR2hzWijOVAvcTvQRihMMvtEi/dljL006so1gcvARvBXr/TSrhlKnw7y/rmXaESST1HnUu8KRQOpX7HE=
  app: tccapp-next-release
