language: python
python:
- '3.6'
addons:
  postgresql: "10.4"
services:
- postgresql
before_script:
  - psql -c 'create database test_db;' -U postgres
env:
  - DATABASE_URL=postgres://postgres@localhost/test_db
install:
- pip install -r requirements.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: EKiXrMz9agRFXmPscQfJqrp4caSTBBt052GOCNmiHdt37WmPjP5u7uJTEj+PErOVfx/Z53+L0J+e+stQYiBQgfYqTRntObPD2dZ9wc4b1kaExFrnrHdth8jQiHtpbRgJKVxJqAkf3Lu2XEx56hiA7XTCiFnFp70BAzVXcnv1cwuycLb73hTR+ikTTw8QF58YzPfM0uqCrZWtQS3JSwAQoGZDlvFc5tpvpW+OBIfDhd30im2pD696PuNcbOtJyH/iRm7+zH1n4FN4yfx128eHQN14lat1dhMIaw9DhthRcTxzsVhysLg5swoS/IN8MGfi3dLWi44gp9V3p98f/o59fLE8aCBrx0u8THGD4amva18Dwsc8PYTtQNleRBFiuKatEIDTlcHqdOZoYeVc78rDpd1AJrGnoDVFeWZuqoI+s1KzKiEnveOQmG6RkKkfTIihjd8FnCKNmQOlCtPgxp9XoXtaeyEdi7jQXckJ3B/Y7JxaacIkgvRrKrpk+y1QEc2dcmtaPY1XPc3v0cDNs7OcQ1gvf+5wW4Vv1M76O5wHslwvJEFF7+ElchvHvdCv94r5QN+lE/AEZa8z8WOuC6LD3ra5jrUKR2hzWijOVAvcTvQRihMMvtEi/dljL006so1gcvARvBXr/TSrhlKnw7y/rmXaESST1HnUu8KRQOpX7HE=
  app: tccapp-next-release
