# Generated by Django 2.1 on 2018-09-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='modality',
            field=models.CharField(choices=[('SMS', 'Semetral'), ('QDR', 'Quadrimestral')], default='QDR', max_length=3),
        ),
    ]
