# Generated by Django 2.1 on 2018-09-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0002_auto_20180903_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='modality',
            field=models.CharField(choices=[('SMS', 'Semestral'), ('QDR', 'Quadrimestral')], default='QDR', max_length=3),
        ),
    ]
