# Generated by Django 2.1 on 2018-09-06 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workgroups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workgroup',
            name='guest',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='workgroup_guest', to=settings.AUTH_USER_MODEL),
        ),
    ]
