# Generated by Django 2.1 on 2018-09-06 23:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workgroups', '0003_auto_20180906_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workgroup',
            name='students',
            field=models.ManyToManyField(related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
