# Generated by Django 2.1.2 on 2018-11-17 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplines', '0003_auto_20180906_1714'),
        ('events', '0002_remove_event_free_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_runned_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('practical_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_event', to='events.Event')),
                ('quarter_discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarter_discipline', to='disciplines.Discipline')),
                ('semester_discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_discipline', to='disciplines.Discipline')),
                ('theoretical_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theoretical_event', to='events.Event')),
            ],
        ),
    ]
