# Generated by Django 2.1.2 on 2018-11-12 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0002_auto_20181109_1931'),
        ('events', '0001_initial'),
        ('workgroups', '0006_workgroup_identifier'),
        ('allocations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='selected_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Room'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='workgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workgroups.Workgroup'),
        ),
    ]
