# Generated by Django 2.1 on 2018-09-10 21:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0002_auto_20180906_1657'),
        ('workgroups', '0004_auto_20180906_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField(default=datetime.date.today)),
                ('main_file', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='submission_files')),
                ('side_file', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='submission_files')),
                ('status', models.CharField(choices=[('NAV', 'Não avaliada'), ('AGS', 'Avaliada pelo co-orientador'), ('AAD', 'Avaliada pelo orientador')], default='NAV', max_length=3)),
                ('public_comments', models.TextField(default='', max_length=500)),
                ('private_comments', models.TextField(default='', max_length=500)),
                ('score', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Activity')),
                ('workgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workgroups.Workgroup')),
            ],
        ),
    ]
